/* System Configuration */
#ifndef SYSTEM_CONFIG__H
#define SYSTEM_CONFIG__H

#define FIRMWARE_VERSION "0.1"
#define WATCHDOG_TIMEOUT_MS 3000
#define SENSOR_PERIOD_MS 1000

#define RUN_STATE_PACKET_FREQUENCY_ms 3000
#define SAFE_STATE_PACKET_FREQUENCY_ms 15000 

#endif // SYSTEM_CONFIG__H