/*         PARADA2 Firmware
    -> Created by: Jakub Farnik
    -> Project creation date: 2024-06-01
    -> Project generated by the Pico SDK Extension for Visual Studio Code
*/
#include <stdio.h>

#include "system/system.h"
#include "system/status.h"



int main(void)
{
    status_t status = system_init();
    if(status != STATUS_OK) {
        printf("System initialization failed with status: %d\n", status);
        return -1;
    }
    for(;;){

    }

    return STATUS_OK;
}
