/*         PARADA2 Firmware
    -> Created by: Jakub Farnik
    -> Project creation date: 2024-06-01
    -> Project generated by the Pico SDK Extension for Visual Studio Code
*/
#include <stdio.h>

#include "system/system.h"
#include "system/status.h"
#include "communication/logging.h"


int main(void)
{
    status_t sys_init_status = system_init();
    if(sys_init_status != STATUS_OK) {
        log_error("System initialization failed", sys_init_status);
        for(;;){
            // Stay here if system initialization fails
            // Add recovery later
        }
    }

    system_run();

    return STATUS_OK;
}
